fullnameOverride: "bluegreen-demo"
replicaCount: 3
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
  hosts:
    - host: acc-blue-green.digitaldev.nl
      paths: 
      - path: /
        backend:
          serviceName: bluegreen-demo
    - host: acc-preview.digitaldev.nl
      paths: 
      - path: /
        backend:
          serviceName: bluegreen-demo-preview

image:
  tag: blue


strategy:
  blueGreen:
    autoPromotionEnabled: false
    activeService: bluegreen-demo
    previewService: bluegreen-demo-preview