apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-demo
  namespace: argocd 
spec:
  destination:
    namespace: bluegreen-demo
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/ivanov-aleksander/rollouts-demo.git'
    targetRevision: HEAD
    path: blue-green
  project: default
