fullnameOverride: "argo-cd"

## Server
server:
  ## Additional command line arguments to pass to argocd-server
  ##
  extraArgs:
   - --insecure

  config:
    repositories: |
      - url: https://github.com/ivanov-aleksander/rollouts-demo.git



  ingress:
    enabled: true

    ## Argo Ingress.
    ## Hostnames must be provided if Ingress is enabled.
    ## Secrets must be manually created in the namespace
    ##
    hosts:
      - argocd.demo.com
    paths:
      - /
